version: "3.8"

services:
  opensearch:
    image: opensearchproject/opensearch:2.14.0
    container_name: opensearch
    environment:
      - discovery.type=${DISCOVERY_TYPE}
      - plugins.security.disabled=${PLUGINS_SECURITY_DISABLED}
      - OPENSEARCH_JAVA_OPTS=${OPENSEARCH_JAVA_OPTS}
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    networks:
      - opensearch
    volumes:
      - osdata:/usr/share/opensearch/data

  dashboards:
    image: opensearchproject/opensearch-dashboards:2.14.0
    container_name: dashboards
    environment:
      - OPENSEARCH_HOSTS=${OPENSEARCH_HOSTS}
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=${DISABLE_SECURITY_DASHBOARDS_PLUGIN}
    ports:
      - "5601:5601"
    depends_on:
      - opensearch
    networks:
      - opensearch

  logstash:
    image: opensearchproject/logstash-oss-with-opensearch-output-plugin:7.16.3
    container_name: logstash
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - ./logs:/logs:ro
    environment:
      LS_JAVA_OPTS: ${LS_JAVA_OPTS}
      LOGSTASH_INPUT_PATH: ${LOGSTASH_INPUT_PATH}
      LOGSTASH_OUTPUT_INDEX: ${LOGSTASH_OUTPUT_INDEX}
    depends_on:
      - opensearch
    networks:
      - opensearch

volumes:
  osdata:

networks:
  opensearch:
    driver: bridge
